# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loadUserDict <- function(filePath, defaultWeight, defaultTag) {
    .Call('cidian_loadUserDict', PACKAGE = 'cidian', filePath, defaultWeight, defaultTag)
}

decode_scel_cpp <- function(file, output, freq, disp) {
    .Call('cidian_decode_scel_cpp', PACKAGE = 'cidian', file, output, freq, disp)
}

