# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loadUserDict <- function(filePath, defaultTag) {
    .Call('cidian_loadUserDict', PACKAGE = 'cidian', filePath, defaultTag)
}

loadSysDict <- function(filePath) {
    .Call('cidian_loadSysDict', PACKAGE = 'cidian', filePath)
}

gen_sys_character <- function(input, disp) {
    .Call('cidian_gen_sys_character', PACKAGE = 'cidian', input, disp)
}

gen_user_character <- function(input, disp) {
    .Call('cidian_gen_user_character', PACKAGE = 'cidian', input, disp)
}

decode_scel_cpp <- function(file, output, tag, disp) {
    .Call('cidian_decode_scel_cpp', PACKAGE = 'cidian', file, output, tag, disp)
}

